name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          composer install

      - name: Download SonarScanner
        run: |
          Invoke-WebRequest -Uri https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-windows.zip -OutFile sonar-scanner.zip
          Expand-Archive -Path sonar-scanner.zip -DestinationPath $env:USERPROFILE\sonar-scanner
          echo "$env:USERPROFILE\sonar-scanner\sonar-scanner-4.6.2.2472-windows\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Run SonarQube analysis
        env:
          SONAR_TOKEN: squ_f30ca774b08ae33c6654194693926eaad5e00264
          SONAR_HOST_URL: http://localhost:9000
        run: |
          sonar-scanner -Dsonar.projectKey=testmila -D sonar.sources=. -D sonar.host.url=http://localhost:9000 -D sonar.token=squ_f30ca774b08ae33c6654194693926eaad5e00264

